version: "3.7"
services:
  monolithic-server:
    image: monolithic-server:latest
    container_name: monolithic-server
    ports:
      - "${MONOLITHIC_SERVER_PORT}:8080"
    environment:
      POSTGRES_IP: ${MONOLITHIC_SERVER_POSTGRES_IP}
      POSTGRES_PORT: ${MONOLITHIC_SERVER_POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_PORT: ${MONOLITHIC_SERVER_REDIS_PORT}

  redis:
    image: redis:alpine
    command: redis-server --port ${REDIS_PORT}
    container_name: monolithic-redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "${REDIS_PORT}:6379"

  postgresql:
    image: postgres:alpine
    container_name: monolithic-pg
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin