name: Monolithic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MODULE_PATH: monolithic

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ env.MODULE_PATH }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run JaCoCo
        run: ./gradlew test jacocoTestReport
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: build/jacoco/reports/html/
